orbs:
  node: circleci/node@4.1.1
  docker: circleci/docker@x.y.z
  jobs:
    pull:
      executor: docker/machine
      steps:
        - checkout
        - docker/pull:
            images: 'ubuntu:16.04,ubuntu:18.04'
version: 2.1
workflows:
  pull-images:
    jobs:
      - pull e3bddc34879c
    
