version: 2.1
jobs:
  TO_flow:
    docker:
      - image: circleci/node:10
    steps:
    - checkout
    - run:
        name: Install npm dependancies 1
        command: | 
        - npm install --save
        - npm init -y
        - node app.js
workflows:
    build_test:
        jobs:
          - TO_flow
    
