orbs:
  docker: circleci/docker@x.y.z
  jobs:
    pull:
      executor: docker/machine
      steps:
        - checkout
        - docker/pull:
            images: 'ubuntu:16.04'
version: 2.1
workflows:
  pull-images:
    jobs:
      docker pull e3bddc34879c

    
